---
output:
  html_document:
        theme: null
        highlight: null
        mathjax: null
---
This tool uses the package terradactyl which was built to use data from the [Bureau of Land Management's Assessment, Inventory, and Monitoring program (AIM)](https://blm.gov/aim). This means that there are certain variables that are required in the input data. If you choose to upload data, you must ensure that these variables exist in your data or else the tool will be unable to calculate statistics from them. These variables are the bare minimum; you may have additional variables in your data. All of these are assumed to be in long format unless otherwise stated.

## Line-Point Intercept
### PrimaryKey
`PrimaryKey` must contain the unique identifier for each sampling event at a sampling location, e.g. a plot visit. All records from the same sampling event must have the same primary key value. If a sampling location was visited more than once, each visit's records should have a unique primary key value.

### code
The variable `code` (all lowercase) must contain the codes for what was intercepted by the pin in each layer at each point along the line/transect, either the species code (e.g., `"ARTR2"`) or surface code (e.g., `"S"`). Valid codes can be found in volume I of the [Monitoring Manual for Grassland, Shrubland, and Savanna Ecosystems](https://www.landscapetoolbox.org/methods-manuals/monitoring-manual-2nd-edition/) under the rules for the line-point intercept method.

### PointNbr
`PointNbr` must contain the ordinal number for the pin drop along its transect, e.g., all records from the first pin drop on a transect would have the value `1` while all records from the second pin drop on that transect would have the value `2`.

### layer
The variable `layer` (all lowercase) must contain the layer on the pin drop that the record comes from. Valid values include `"TopCanopy"`, `"Lower#"` where each subsequent lower canopy layer uses the next ordinal number (e.g., `"Lower1"`), and `"SoilSurface"`.

## Height
### PrimaryKey
PrimaryKey must contain the unique identifier for each sampling event at a sampling location, e.g. a plot visit. All records from the same sampling event must have the same primary key value. If a sampling location was visited more than once, each visit's records should have a unique primary key value.

## Gap
### PrimaryKey
PrimaryKey must contain the unique identifier for each sampling event at a sampling location, e.g. a plot visit. All records from the same sampling event must have the same primary key value. If a sampling location was visited more than once, each visit's records should have a unique primary key value.

## Soil Stability
### PrimaryKey
PrimaryKey must contain the unique identifier for each sampling event at a sampling location, e.g. a plot visit. All records from the same sampling event must have the same primary key value. If a sampling location was visited more than once, each visit's records should have a unique primary key value.