---
output:
  html_document:
        theme: null
        highlight: null
        mathjax: null
---
## Indicator configuration

### Line-Point Intercept
#### Any hit versus first hit
There are two options for which "hit" to calculate from with LPI data. When a pin is dropped during LPI, all intercepted canopy layers and the soil surface are recorded. When calculating using "any hit" then every layer is considered as contributing to cover while ""first hit" only considers the topmost recorded hit. For example, if a pin first touches a perennial forb then an annual grass, using "first hit" would ignore the annual grass record and that would not contribute to the percent cover by annual grass because it was not the topmost recorded cover. If using "any hit" then the perennial forb would contribute to cover by perennial forbs *and* the annual grass would contribute to to cover by annual grasses.

When using "first hit" all your calculated cover values on a plot will sum to 100%. When using "any hit" 100% is the minimum total cover possible; if any pin drops recorded more than one hit, then the sum of cover values will exceed 100%. "Any hit" is the default because it provides the most information from the data and doesn't exclude any records, offering the most comprehensive characterization. "First hit" was added as an option for those working with remote sensing products who had requested something that might approximate the aerial or satellite view of the landscape, however it can be argued that "any hit" is in fact more representative.

#### Grouping variables
These are additional variables beyond the sampling location to group the data by for calculating cover. The default behavior is to group by sampling location and calculate the percent cover for that location. In order to calculate finer-grained cover values, additional grouping variables need to be selected. For example, in order to calculate cover by species for each sampling location, the variable containing the species codes or names would need to be selected. The selected variables are additive, so selecting both a variable containing plant duration and a variable containing plant growth habit would result in cover being calculated for each combination of those two, e.g., annual forbs and perrennial grasses.

#### Summarization unit
Cover can be calculated by plot (each unique PrimaryKey value) or by line (each unique combination of PrimaryKey and LineKey). It is generally not recommended that you calculate by line, especially if you have fewer than 100 records per line.

#### Output format
The output can be either long or wide. In long format, each *observed* indicator is represented by a row. This means that if you have supplied `code` as your grouping variable, only those codes which appeared on your summarization unit will have a row representing them. This is in contrast to wide format in which every possible indicator has a column in the results and they will have a value of 0 for summarization units where they were not observed.


### Gap
#### Breaks
Gap data are classified into size classes and the indicators reported are percent of the sampling location composed of gaps in each size class. The break values define the minimum gap size and what values to split the data at. The values must be listed in ascending order and separated by commas. The first value acts as the minimum gap size while the maximum gap size is infinity. As an example, in order to calculate cover for three size classes, one from 20 cm to 50 cm, one for 51 to 100 cm, and one for greater than 100 cm, the breaks would be ```20, 51, 101```.

#### Gap type
There are three available types of gap that can be calculated. They are:

* Canopy - Gaps in canopy, considering both annual and perennial plants. This uses only records where the variable ```RecType``` is ```"C"```
* Basal - Gaps between plant bases at the soil surface, considering both annual and perennial plants. This uses only records where the variable ```RecType``` is ```"B"```
* Perennial canopy - Gaps in canopy, considering only perennial plants. This uses only records where the variable ```RecType``` is ```"P"```

#### Summarization unit
Gaps can be calculated at the plot level or per transect/line. Calculating by plot will group the results by the variable ```PrimaryKey``` while calculating by line will group the results by both ```PrimaryKey``` and ```LineKey```

#### Output format
The output can be either long or wide. In long format, each row is represents one statistic for your summarization unit, e.g., a row would be your summarization unit, the gap size class, the statistic name, and the statistic value. In wide format, each row is a single summarization unit and each statistic has a column.

### Height
#### Statistic
There are two available height statistics: mean and maximum. Both are calculated per-group, so by default they are the mean or maximum height value observed at a sampling location.

### Soil Stability
#### Vegetative cover grouping
Soil stability data includes the vegetative cover at the location where a soil sample was collected. The mean can be calculated in a few ways using vegetative cover. It can be summarized by considering:

* For soil samples with ```all cover types```
* For only those soil samples that had ```perennial cover```
* For only those soil samples that did not have perennial cover (considered ```no cover```)
* All soil stability samples, but ```by cover type```, producing a mean for each cover type