---
format: html
editor: visual
---

The Rangeland Indicator Calculator calculates ecological indicators from monitoring data collected following methods in the *Monitoring Manual for Grassland, Shrubland, and Savannah Ecosystems* using the R package [terradactyl](https://github.com/Landscape-Data-Commons/terradactyl). ([McCord et al. 2022](https://www.sciencedirect.com/science/article/pii/S1470160X22009840)) These indicators can be used for interpreting the data and making land management decisions. The data can either be retrieved from the [Landscape Data Commons](https://landscapedatacommons.org) (LDC) through this interface or uploaded instead.

1)  Select the Data Type, or method, that you would like to use to calculate indicators. Line-point intercept can be used to calculate vegetation and ground cover; height provides indicators of vegetation height; gap intercept provides indicators cover of gaps between vegetation; and soil stability provides indicators of wet soil aggregate stability.

2)  Select the type of data you will be working with and either upload a CSV file containing the data or download the appropriate data from the LDC using the pane on the left. If you are uploading data, check the help tab to find the formatting rules. If downloading from the LDC through this tool, you must specify how you're searching for data. You can search the LDC spatially with your own polygons by uploading a ZIP file containing the files that make up a polygon shapefile or a ZIP containing a geodatabase with the polygons as a feature class. If you would rather, you can instead search by ecological site IDs, project keys, or primary keys.

3)  In the "Data configuration" tab, confirm the variables in your data which correspond to the required variables; they should be correct already if your data come from the LDC. Optionally with LPI and height data, you may choose to also add species information via joining from a lookup table. If you make a mistake when joining species information, you can reset your data under the "Data" tab.

4)  In the "Indicator calculation" tab select the options for the indicators you wish to calculate then use the "Calculate" button to produce results in the "Results" tab.
